# Values de produção do wallet
name: wallet

image:
  repository: us-central1-docker.pkg.dev/staging-platform-510420/docker-images/wallet
  pullPolicy: IfNotPresent

service:
  port: 8080
  type: ClusterIP

env:
  - name: PORT
    value: "8080"
  - name: LEDGER_URL
    value: "http://ledger:8080"

resources:
  requests:
    cpu: "200m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
