apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ include "service-chart.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
